docs(readme): fix the usage example
Before this patch, when trying to run the README example we get the
following error:

    % go run ./main.go
    # command-line-arguments
    ./main.go:13:43: too many arguments in call to ch.Dial
        have (context.Context, string, ch.Options)
        want (context.Context, ch.Options)

See also 9cc1b6eec4260ab17ae4425dad698911b0d4083f ("refactor: make address optional")
which removed the address field of Dial.

Signed-off-by: Alexandre Perrin <alex@isovalent.com>